package com.example.fraud.common.event;

public enum FraudRuleCode {
    AMOUNT_THRESHOLD,
    NIGHT_TIME_TRANSACTION,
    SUSPICIOUS_LOCATION,
    RAPID_TRANSACTION_COUNT,
    WINDOW_AMOUNT_SUM,
    HIGH_AMOUNT,
    VELOCITY,
    NEW_DEVICE,
    LOCATION_CHANGE
}
