create table dead_letter_events (
    id bigint generated by default as identity primary key,
    event_id varchar(100) not null,
    trace_id varchar(100) not null,
    user_id varchar(100) not null,
    source_topic varchar(100) not null,
    source_partition integer not null,
    source_offset bigint not null,
    dlt_topic varchar(100) not null,
    failure_stage varchar(50) not null,
    error_type varchar(200) not null,
    error_message text,
    payload_json text not null,
    status varchar(30) not null,
    reprocess_attempts integer not null default 0,
    last_reprocessed_at timestamp with time zone,
    discarded_at timestamp with time zone,
    discard_reason text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_dead_letter_events_source_offset unique (source_topic, source_partition, source_offset),
    constraint ck_dead_letter_events_status check (
        status in ('PENDING', 'REPROCESSING', 'REPROCESSED', 'DISCARDED', 'REPROCESS_FAILED')
    ),
    constraint ck_dead_letter_events_reprocess_attempts check (reprocess_attempts >= 0)
);

create index idx_dlt_event_id on dead_letter_events (event_id);
create index idx_dlt_status_created_at on dead_letter_events (status, created_at);
create index idx_dlt_trace_id on dead_letter_events (trace_id);
create index idx_dlt_failure_stage_created_at on dead_letter_events (failure_stage, created_at);
