create table admin_audit_logs (
    id bigint generated by default as identity primary key,
    actor varchar(100) not null,
    action varchar(100) not null,
    target_type varchar(50) not null,
    target_id varchar(100) not null,
    request_id varchar(100),
    trace_id varchar(100),
    result varchar(30) not null,
    reason text,
    metadata_json text,
    created_at timestamp with time zone not null,
    constraint ck_admin_audit_logs_result check (result in ('SUCCESS', 'FAILED'))
);

create index idx_admin_audit_actor_created_at on admin_audit_logs (actor, created_at);
create index idx_admin_audit_action_created_at on admin_audit_logs (action, created_at);
create index idx_admin_audit_target on admin_audit_logs (target_type, target_id);
create index idx_admin_audit_trace_id on admin_audit_logs (trace_id);
