create table transaction_event_receipts (
    id bigint generated by default as identity primary key,
    event_id varchar(100) not null,
    schema_version varchar(20) not null,
    user_id varchar(100) not null,
    account_id varchar(100) not null,
    event_type varchar(50) not null,
    amount numeric(19, 2) not null,
    currency varchar(3) not null,
    merchant_id varchar(100),
    device_id varchar(100),
    location varchar(100),
    event_time timestamp with time zone not null,
    received_at timestamp with time zone not null,
    trace_id varchar(150) not null,
    status varchar(30) not null,
    publish_error_message varchar(500),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_transaction_event_receipts_event_id unique (event_id)
);

create index idx_transaction_event_receipts_user_id on transaction_event_receipts (user_id);
create index idx_transaction_event_receipts_received_at on transaction_event_receipts (received_at);
create index idx_transaction_event_receipts_status on transaction_event_receipts (status);
