create table event_processing_logs (
    id bigint generated by default as identity primary key,
    event_id varchar(100) not null,
    trace_id varchar(150) not null,
    user_id varchar(100) not null,
    topic varchar(100) not null,
    partition_no integer not null,
    offset_no bigint not null,
    consumer_group_id varchar(100) not null,
    status varchar(30) not null,
    error_message varchar(500),
    received_at timestamp with time zone not null,
    processed_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_event_processing_logs_topic_partition_offset unique (topic, partition_no, offset_no)
);

create index idx_event_processing_logs_event_id on event_processing_logs (event_id);
create index idx_event_processing_logs_trace_id on event_processing_logs (trace_id);
create index idx_event_processing_logs_processed_at on event_processing_logs (processed_at);
