package com.example.fraud.api.support.exception;

public enum ApiErrorCode {
    INVALID_TRANSACTION_EVENT,
    DUPLICATE_TRANSACTION_EVENT,
    DATABASE_WRITE_FAILED,
    EVENT_NOT_FOUND,
    FRAUD_RESULT_NOT_FOUND,
    DLQ_EVENT_NOT_FOUND,
    DLQ_EVENT_NOT_REPROCESSABLE,
    DLT_STATE_CONFLICT,
    KAFKA_PUBLISH_FAILED,
    INTERNAL_ERROR
}
